import Foundation

struct Constants {
    
    struct IconNames {
        static let icon1 = "George Washington"
        static let icon2 = "John Adams"
        static let icon3 = "Thomas Jefferson"
        static let icon4 = "James Madison"
        static let icon5 = "James Monroe"
        static let icon6 = "John Quincy Adams"
        static let icon7 = "Andrew Jackson"
        static let icon8 = "Martin Van Buren"
        static let icon9 = "William Henry Harrison"
        static let icon10 = "John Tyler"
        static let icon11 = "James K. Polk"
        static let icon12 = "Zachary Taylor"
        static let icon13 = "Millard Fillmore"
        static let icon14 = "Franklin Pierce"
        static let icon15 = "James Buchanan"
        static let icon16 = "Abraham Lincoln"
        static let icon17 = "Andrew Johnson"
        static let icon18 = "Ulysses S. Grant"
        static let icon19 = "Rutherford B. Hayes"
        static let icon20 = "James Garfield"
        static let icon21 = "Chester A. Arthur"
        static let icon22 = "Grover Cleveland"
        static let icon23 = "Benjamin Harrison"
        static let icon24 = "William McKinley"
        static let icon25 = "Theodore Roosevelt"
        static let icon26 = "William Howard Taft"
        static let icon27 = "Woodrow Wilson"
        static let icon28 = "Warren G. Harding"
        static let icon29 = "Calvin Coolidge"
        static let icon30 = "Herbert Hoover"
        static let icon31 = "Franklin D. Roosevelt"
        static let icon32 = "Harry S. Truman"
        static let icon33 = "Dwight D. Eisenhower"
        static let icon34 = "John F. Kennedy"
        static let icon35 = "Lyndon B. Johnson"
        static let icon36 = "Richard M. Nixon"
        static let icon37 = "Gerald R. Ford"
        static let icon38 = "Jimmy Carter"
        static let icon39 = "Ronald Reagan"
        static let icon40 = "George H. W. Bush"
        static let icon41 = "Bill Clinton"
        static let icon42 = "George W. Bush"
        static let icon43 = "Barack Obama"
        static let icon44 = "Donald Trump"
    }
    
    struct ImageNames {
        static let image1 = "George Washington"
        static let image2 = "John Adams"
        static let image3 = "Thomas Jefferson"
        static let image4 = "James Madison"
        static let image5 = "James Monroe"
        static let image6 = "John Quincy Adams"
        static let image7 = "Andrew Jackson"
        static let image8 = "Martin Van Buren"
        static let image9 = "William Henry Harrison"
        static let image10 = "John Tyler"
        static let image11 = "James K. Polk"
        static let image12 = "Zachary Taylor"
        static let image13 = "Millard Fillmore"
        static let image14 = "Franklin Pierce"
        static let image15 = "James Buchanan"
        static let image16 = "Abraham Lincoln"
        static let image17 = "Andrew Johnson"
        static let image18 = "Ulysses S. Grant"
        static let image19 = "Rutherford B. Hayes"
        static let image20 = "James Garfield"
        static let image21 = "Chester A. Arthur"
        static let image22 = "Grover Cleveland"
        static let image23 = "Benjamin Harrison"
        static let image24 = "William McKinley"
        static let image25 = "Theodore Roosevelt"
        static let image26 = "William Howard Taft"
        static let image27 = "Woodrow Wilson"
        static let image28 = "Warren G. Harding"
        static let image29 = "Calvin Coolidge"
        static let image30 = "Herbert Hoover"
        static let image31 = "Franklin D. Roosevelt"
        static let image32 = "Harry S. Truman"
        static let image33 = "Dwight D. Eisenhower"
        static let image34 = "John F. Kennedy"
        static let image35 = "Lyndon B. Johnson"
        static let image36 = "Richard M. Nixon"
        static let image37 = "Gerald R. Ford"
        static let image38 = "Jimmy Carter"
        static let image39 = "Ronald Reagan"
        static let image40 = "George H. W. Bush"
        static let image41 = "Bill Clinton"
        static let image42 = "George W. Bush"
        static let image43 = "Barack Obama"
        static let image44 = "Donald Trump"
    }
}
